const API_ORIGIN = process.env.REACT_APP_API_ORIGIN || "";
const API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT || "";

const APP_ORIGIN = process.env.REACT_APP_ORIGIN;

const CLOUDINARY_CLOUD_NAME = process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.REACT_APP_CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.REACT_APP_CLOUDINARY_API_SECRET;
const CLOUDINARY_API_UPLOAD_PRESET =
  process.env.REACT_APP_CLOUDINARY_API_UPLOAD_PRESET;

const FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY || "";
const FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN || "";
const FIREBASE_PROJECT_ID = process.env.REACT_APP_FIREBASE_PROJECT_ID || "";
const FIREBASE_STORAGE_BUCKET =
  process.env.REACT_APP_FIREBASE_STORAGE_BUCKET || "";
const FIREBASE_MESSAGING_SENDER_ID =
  process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID || "";
const FIREBASE_APP_ID = process.env.REACT_APP_FIREBASE_APP_ID || "";
const FIREBASE_MEASUREMENT_ID =
  process.env.REACT_APP_FIREBASE_MEASUREMENT_ID || "";

export {
  API_ORIGIN,
  API_ENDPOINT,
  APP_ORIGIN,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_API_UPLOAD_PRESET,
  CLOUDINARY_CLOUD_NAME,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
};
